version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - kpo2

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - kpo2

  storing:
    build:
      context: ./storing_service
      dockerfile: Dockerfile
    depends_on:
      - db
      - minio
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "8081:8081"
    networks:
      - kpo2

  analysis:
    build:
      context: .
      dockerfile: ./analysis_service/Dockerfile
    depends_on:
      - db
      - storing
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      STORING_SERVICE_URL: http://storing:8081
    ports:
      - "8082:8082"
    networks:
      - kpo2

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - storing
      - analysis
      - minio
    environment:
      ANALYSIS_SERVICE_URL: http://analysis:8082
      STORING_SERVICE_URL: http://storing:8081
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "8000:8000"
    networks:
      - kpo2

volumes:
  db-data:
  minio-data:

networks:
  kpo2:
    driver: bridge
